### ISSUE TITLE
Stepper broken due to change in Adafruit_CircuitPython_Motor

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_Crickit#15]
Started here:
https://forums.adafruit.com/viewtopic.php?f=8&t=148916
and verified. This PR:
https://github.com/adafruit/Adafruit_CircuitPython_Motor/pull/23/files
changed the way the `frequency` value is checked. It now throws an Error instead of changing it.

The stepper setup here needs to set `frequency` on its `PWMOut` objects. This might be made easier if `frequency` could be passed in to PWMOut constructor:  
https://github.com/adafruit/Adafruit_CircuitPython_seesaw/blob/master/adafruit_seesaw/pwmout.py#L29

**Comment by ladyada** [comment]
@siddacious heya can you check this and revert ? ive been swamped and unable to test

**Comment by siddacious** [comment]
Yup, I'll take a look.

**Comment by siddacious** [comment]
OOf. My bad. :|

**Comment by ladyada** [comment]
hiya this should be all fixed now!
