### ISSUE TITLE
How to use this library on a raspberry pi but with ubuntu instead of raspbian ?

### ISSUE THREAD

**Issue by lefuturiste** [adafruit/Adafruit_CircuitPython_Crickit#18]
My issue is that, I have a Raspberry Pi Model B+ but with a ubuntu distro on it.

I can detect my Crickit hat:

![](https://i.imgur.com/1dNRgWj.png) 

but I can't import the crickit python lib:

![](https://i.imgur.com/9UqLQp6.png)

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.6/site-packages/adafruit_crickit.py", line 46, in <module>
    import board
  File "/home/ubuntu/.local/lib/python3.6/site-packages/board.py", line 89, in <module>
    raise NotImplementedError("Board not supported")
NotImplementedError: Board not supported
```

This is my environment:
![](https://i.imgur.com/xG83xmr.png)

**Comment by ladyada** [comment]
yeah we do not have board detection support for Ubuntu - please use raspbian 
or you can add board detection support to this repo https://github.com/adafruit/Adafruit_Python_PlatformDetect

**Comment by lefuturiste** [comment]
okay thanks
