### ISSUE TITLE
Reusing crickit I2C instance

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_Crickit#19]
`crickit` creates its own `I2C` instance, instead of using `board.I2C()`. It was written before `board.I2C()` existed.

It should use `board.I2C()` if possible (maybe we can assume it exists now in all supported versions of CircuitPython). This will allow external I2C devices to be used easily.

Alternatively, or in addition, we could have a property that returns `crickit.seesaw.i2c_device` and/or the underlying `i2c'.

tagging @caternuson, since this has come up in support issues.

**Comment by caternuson** [comment]
It's currently created conditionally:
```python
if "SCL" in dir(board):
    crickit = Crickit(Seesaw(busio.I2C(board.SCL, board.SDA))) # pylint: disable=invalid-name
```
Could we just change that up a bit:
```python
if "I2C" in dir(board):
    crickit = Crickit(Seesaw(board.I2C())) # pylint: disable=invalid-name
```

**Comment by dhalbert** [comment]
I looked, and `board.I2C()` was added in 3.x. So that seems fine: we don't need to support 2.x any more. We could still add a `.i2c` property but it's not vital.

**Comment by caternuson** [comment]
Older versions could still get there, right? Would just need to manually setup the crickit instance after importing.

And the `.i2c` property idea might be confusing. There'd be two different `foo_i2c_sensor()` init's depending on if crickit is being used or not.

**Comment by dhalbert** [comment]
> Older versions could still get there, right? Would just need to manually setup the crickit instance after importing.

Right.
