### ISSUE TITLE
Drive terminal use cases

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_Crickit#3]
Drive terminal support is just PWM, and you change the duty cycle. I just took this from the Learn Guide examples. What are other use cases for Drive terminals and what kind of API would be convenient?

**Comment by ladyada** [comment]
only other thing you can do is connecting a unipolar stepper.

**Comment by dhalbert** [comment]
Drive terminals can only be PWM. I added a `.fraction` to seesaw `PWMOut` to make it easier to set them full on:
```
from adafruit_crickit.crickit import crickit
from adafruit_crickit.terminals import *

drive1 = crickit.pwm_out(CPX_DRIVE1)
# Turn Drive 1 on 100%.
drive1.fraction = 1.0
```
