### ISSUE TITLE
drive stepper has peculiar #ings

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_Crickit#8]
https://github.com/adafruit/Adafruit_CircuitPython_Crickit/blob/f948e09d38aaa8d3f59350372388cd5d603f95a6/adafruit_crickit.py#L240

instead of `(_DRIVE1, _DRIVE2, _DRIVE3, _DRIVE4)` should be  `(_DRIVE1, _DRIVE3, _DRIVE2, _DRIVE4)` which makes the wiring trivial and matches guide :)

ditto for the feather getter below it, maybe make DRIVE_STEPPER = (_DRIVE1, _DRIVE3, _DRIVE2, _DRIVE4)?

**Comment by dhalbert** [comment]
Thanks, will fix - I didn't have a stepper to test.

**Comment by dhalbert** [comment]
Fixed by 21dec61035621838e146ede85cd6068ae0d7b307. Got a bipolar and unipolar stepper to test. Tested on CPX and Feather Crickits.
